server:
  port: 8090

spring:
  application:
    name: eclipse-link-example
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/eclipse_db
    username: link
    password: eclipse
    hikari:
      auto-commit: true
      schema: eclipse_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS eclipse_schema
      connection-timeout: 10000
      maximum-pool-size: 10

logging:
  level:
    org:
      eclipse:
        persistence: debug
